---
- hosts: all
  tasks:
    - name: Install EPEL Repo package from standard repo
      yum:
        name: epel-release
        state: installed

    - name: Install Borg backup 
      yum:
        name: borgbackup
        state: installed
        update_cache: yes

    - name: Generate /etc/hosts file
      template:
        src: hosts.j2
        dest: /etc/hosts


- hosts: server
  vars:
    user: backup
    group: backup
    home: /home/backup
    pool: "{{ home }}/repos"
    client_host: client.localdomain

  tasks:
    - name: Create backup group 
      group: 
        name: "{{ group }}" 
        state: present

    - name: Add backup user
      user:
        name: "{{user}}"
        shell: /bin/bash
        home: "{{ home }}"
        createhome: yes
        group: "{{ group }}"
        groups: ''
        state: present

    - name: Extract client's pub key
      shell: "ssh-keyscan -t rsa {{client_host}} | sed 's/^[^ ]* //'"
      register: pub_key

    - name: Add client's pub key to authorized keys for backup user
      authorized_key:
        user: "{{ user }}"
        key: "{{pub_key.stdout}}"
        state: present
        key_options: 'command="cd {{ pool }}/{{client_host}};borg serve --restrict-to-path {{ pool }}/{{client_host}}",restrict'

    - name: Set permissions for authorized_keys file
      file: 
        path: "{{ home }}/.ssh/authorized_keys" 
        owner: "{{ user }}" 
        group: "{{ group }}" 
        mode: 0600 
        state: file
    
    - name: Set permissions for backup folder
      file: 
        path: "{{ pool }}/{{client_host}}" 
        owner: "{{ user }}" 
        group: "{{ group }}" 
        mode: 0700 
        state: directory 

# - hosts: client
#   tasks: